name: Dependabot Auto-PR Workflow

on:
  schedule:
    - cron: '11 20 * * *' # Runs everyday at 11:20pm
  repository_dispatch:
    types: [dependabot_alert_created]

jobs:
  create_auto_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create Auto-PR
        uses: dependabot/create-merge-request-action@v2.5.0
        with:
          dependabot-github-token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}