version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "00:15"
      timezone: "Africa/Tunis"
    labels:
      - 'dependencies'
      - 'critical updates'
    open-pull-requests-limit: 1
