version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "00:23"
      timezone: "Africa/Tunis"
    commit-message:
      prefix: "[VERSION UPDATE] "
    labels:
      - 'dependencies'
      - 'version update'
    open-pull-requests-limit: 5
