name: Dependabot Auto-PR Workflow

on:
  push:
    branches:
      - master

jobs:
  create_auto_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Dependabot alerts
        uses: dependabot/dependabot-script@main
        with:
          dependencies: all
          directory: '/frontend'

