name: Dependabot Auto-PR Workflow

on:
  repository_dispatch:
    types: [dependabot_alert_created]

jobs:
  create_auto_pr:
    if: ${{ github.event.client_payload.alert.metadata.vulnerabilities[0].severity == 'low' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Auto Depandabot PR
        uses: dependabot/create-merge-request-action@v2.5.0
        with:
          dependabot-github-token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
